name: CI

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm run serve
      env:
        VUE_APP_FIREBASE_APP_API_KEY: ${{ secrets.VUE_APP_FIREBASE_APP_API_KEY }}
        VUE_APP_FIREBASE_APP_AUTH_DOMAIN: ${{ secrets.VUE_APP_FIREBASE_APP_AUTH_DOMAIN }}
        VUE_APP_FIREBASE_APP_DATABASE_URL: ${{ secrets.VUE_APP_FIREBASE_APP_DATABASE_URL }}
        VUE_APP_FIREBASE_APP_PROJECT_ID: ${{ secrets.VUE_APP_FIREBASE_APP_PROJECT_ID }}
        VUE_APP_FIREBASE_APP_STORAGE_BUCKET: ${{ secrets.VUE_APP_FIREBASE_APP_STORAGE_BUCKET }}
        VUE_APP_FIREBASE_APP_MESSAGING_SENDER_ID: ${{ secrets.VUE_APP_FIREBASE_APP_MESSAGING_SENDER_ID }}
        VUE_APP_FIREBASE_APP_APP_ID: ${{ secrets.VUE_APP_FIREBASE_APP_APP_ID }}
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
